NEWS_SOURCES = [
    # Существующие RSS-источники
    {
        "name": "World Steel Association",
        "type": "rss",
        "url": "https://worldsteel.org/feed/",
    },
    {
        "name": "Metal World Insight",
        "type": "rss",
        "url": "https://metalworldinsight.com/feed",
    },
    {
        "name": "Steel Technology Blog",
        "type": "rss",
        "url": "https://blog.steel-technology.com/feed",
    },
    {
        "name": "911 Metallurgist",
        "type": "rss",
        "url": "https://www.911metallurgist.com/feed/",
    },
    {
        "name": "Mining.com",
        "type": "rss",
        "url": "https://www.mining.com/feed/",
    },
    {
        "name": "MetallPlace",
        "type": "rss",
        "url": "https://metallplace.ru/rss.xml",
    },
    {
        "name": "Steel Times International",
        "type": "rss",
        "url": "https://www.steeltimesint.com/rss",
    },
    {
        "name": "MEPS Steel",
        "type": "rss",
        "url": "https://www.mepsinternational.com/rss/news.xml",
    },
    {
        "name": "AzoMaterials Metals",
        "type": "rss",
        "url": "https://www.azom.com/rss/news.aspx",
    },
    {
        "name": "The Fabricator",
        "type": "rss",
        "url": "https://www.thefabricator.com/rss/news",
    },
    {
        "name": "Interfax",
        "type": "rss",
        "url": "https://www.interfax.ru/rss.asp",
    },
    
    # Новые источники от заказчика - RSS
    {
        "name": "Metalinfo.ru - Чёрные металлы",
        "type": "rss",
        "url": "https://www.metalinfo.ru/ru/news/rferrous.rss",
        "always_include": True,
    },
    {
        "name": "Metalinfo.ru - Зарубежные новости",
        "type": "rss",
        "url": "https://www.metalinfo.ru/ru/news/rferrousabroad.rss",
        "always_include": True,
    },
    {
        "name": "Metaltorg.ru",
        "type": "html",
        "url": "https://www.metaltorg.ru/news/market_index.php",
        "selector": ".news-block, .news-item, article.news",
        "title_selector": "h2.news-title, h2 a, a.news-title",
        "link_selector": "h2.news-title a, h2 a, a",
        "description_selector": ".news-annotation, .description, .preview",
        "always_include": True,
        "render_js": True,
    },
    {
        "name": "World Steel - Пресс-релизы",
        "type": "rss",
        "url": "https://worldsteel.org/feed/",
    },
    {
        "name": "Metal.com",
        "type": "html",
        "url": "https://news.metal.com/list/latest/steel-iron-ore",
        "selector": ".news-item, article, .article-item",
        "title_selector": "a.news-title, h3 a, .title a",
        "link_selector": "a.news-title, h3 a, .title a",
        "description_selector": ".description, .preview, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "MySteel",
        "type": "html",
        "url": "https://www.mysteel.net/",
        "selector": ".news-item, article, .article",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .summary, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Kallanish",
        "type": "html",
        "url": "https://www.kallanish.com/en/",
        "selector": ".article-item, article, .news-item",
        "title_selector": "a, h3 a, h2 a",
        "link_selector": "a, h3 a, h2 a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "BigMint",
        "type": "html",
        "url": "https://www.bigmint.co/",
        "selector": ".article, .news-item, article",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Prometall",
        "type": "html",
        "url": "https://www.prometall.info/",
        "selector": ".news-item, article, .article",
        "title_selector": "a.news-title, h3 a, .title a",
        "link_selector": "a.news-title, h3 a, .title a",
        "description_selector": ".description, .preview, p",
        "always_include": True,
        "render_js": True,
    },
    {
        "name": "Северсталь",
        "type": "html",
        "url": "https://severstal.com/rus/media/archive/",
        "selector": ".news-item, .press-release, article, .news-card",
        "title_selector": "h3 a, h2 a, .title a, a.title",
        "link_selector": "h3 a, h2 a, .title a, a.title",
        "description_selector": ".excerpt, .description, .preview, .summary",
        "always_include": True,
        "render_js": True,
    },
    {
        "name": "ММК",
        "type": "html",
        "url": "https://mmk.ru/ru/press-center/news/",
        "selector": ".news-item, .news-card, article, .press-item",
        "title_selector": "h3 a, h2 a, .title a, a.title",
        "link_selector": "h3 a, h2 a, .title a, a.title",
        "description_selector": ".excerpt, .description, .preview, .summary",
        "always_include": True,
        "render_js": True,
    },
    {
        "name": "ЕВРАЗ",
        "type": "html",
        "url": "https://www.evraz.com/ru/",
        "selector": ".news-item, article, .news-card",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .preview, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Металлоинвест",
        "type": "html",
        "url": "https://www.metalloinvest.com/media/press-releases/",
        "selector": ".press-release, article, .news-item",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Baowu Group",
        "type": "html",
        "url": "https://www.baowugroup.com/media_center/news",
        "selector": ".news-item, article, .article",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "HbisCo",
        "type": "html",
        "url": "https://www.hbisco.com/en/news/group/t698",
        "selector": ".news-item, article, .article",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "POSCO",
        "type": "html",
        "url": "https://www.posco.co.kr/homepage/docs/kor7/jsp/prcenter/press/s91c600100l.jsp",
        "selector": ".news-item, article, tr.news",
        "title_selector": "a, td a",
        "link_selector": "a, td a",
        "description_selector": ".description, .excerpt",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "ArcelorMittal",
        "type": "html",
        "url": "https://corporate.arcelormittal.com/media/",
        "selector": ".news-item, article, .press-release",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Nippon Steel",
        "type": "html",
        "url": "https://www.nipponsteel.com/newsroom/",
        "selector": ".news-item, article, .news-article",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "render_js": True,
    },
    {
        "name": "Tata Steel",
        "type": "html",
        "url": "https://www.tatasteel.com/media/",
        "selector": ".news-item, article, .press-release",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Vale",
        "type": "html",
        "url": "https://vale.com/",
        "selector": ".news-item, article, .press-release",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
    {
        "name": "Rio Tinto",
        "type": "html",
        "url": "https://www.riotinto.com/en/news/releases",
        "selector": ".news-item, article, .press-release",
        "title_selector": "a, h3 a, .title a",
        "link_selector": "a, h3 a, .title a",
        "description_selector": ".description, .excerpt, p",
        "always_include": True,
        "use_proxy": True,
        "render_js": True,
    },
]
