NEWS_SOURCES = [
    {
        "name": "Metalinfo.ru",
        "type": "rss",
        "url": "https://www.metalinfo.ru/ru/news/rss",
    },
    {
        "name": "RBC Металлургия",
        "type": "rss",
        "url": "https://rssexport.rbc.ru/rbcnews/news/20/full.rss",
    },
    {
        "name": "SteelOrbis",
        "type": "rss",
        "url": "https://www.steelorbis.com/rss/news.xml",
    },
    {
        "name": "Mining.com",
        "type": "rss",
        "url": "https://www.mining.com/feed/",
    },
    {
        "name": "Metal Bulletin",
        "type": "rss",
        "url": "https://www.fastmarkets.com/rss-feeds/metals",
    },
    {
        "name": "НЛМК",
        "type": "html",
        "url": "https://nlmk.com/ru/media-center/news/",
        "selector": "article.news-item",
        "title_selector": ".news-item__title",
        "link_selector": "a",
        "description_selector": ".news-item__text",
    },
    {
        "name": "Северсталь",
        "type": "html",
        "url": "https://www.severstal.com/rus/media/news/",
        "selector": "div.news-list-item",
        "title_selector": ".news-list-item__title",
        "link_selector": "a",
        "description_selector": ".news-list-item__text",
    },
    {
        "name": "ММК",
        "type": "html",
        "url": "https://mmk.ru/press_center/news/",
        "selector": "div.news-item",
        "title_selector": ".news-item__title",
        "link_selector": "a",
        "description_selector": ".news-item__description",
    },
    {
        "name": "Reuters Commodities",
        "type": "rss",
        "url": "https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best",
    },
    {
        "name": "Металлоснабжение и сбыт",
        "type": "rss",
        "url": "https://www.metalinfo.ru/ru/news/rss",
    },
    {
        "name": "World Steel Association",
        "type": "rss",
        "url": "https://worldsteel.org/feed/",
    },
    {
        "name": "Steel Times International",
        "type": "rss",
        "url": "https://www.steeltimesint.com/rss",
    },
    {
        "name": "МИСиС Новости",
        "type": "html",
        "url": "https://misis.ru/news/",
        "selector": "div.news-card",
        "title_selector": ".news-card__title",
        "link_selector": "a",
        "description_selector": ".news-card__text",
    },
    {
        "name": "Интерфакс Металлургия",
        "type": "rss",
        "url": "https://www.interfax.ru/rss.asp",
    },
    {
        "name": "Metal Expert",
        "type": "rss",
        "url": "https://www.metalexpert.com/rss/news.xml",
    },
    {
        "name": "Ассоциация Сталь",
        "type": "html",
        "url": "https://www.steel-industry.ru/news/",
        "selector": "div.news-list__item",
        "title_selector": ".news-list__title",
        "link_selector": "a",
        "description_selector": ".news-list__description",
    },
]
